### ISSUE TITLE
Demo: some menu links change url but not the content

### ISSUE THREAD

**Issue by hpvd** [beenotung/ts-liveview#10]
Demo: Menu links to
- editor
- auto-complete

change url but not the content.

Reloading site loads the page content matching the url

seen in FF and chrome

please see attachment:
![2022-06-14_22h25_42](https://user-images.githubusercontent.com/5681880/173682907-070a24d0-cd48-411c-bf9b-5eedd6e05ad2.png)

**Comment by beenotung** [comment]
Thanks for reporting, I can reproduce this bug.
Going to figure out why

**Comment by beenotung** [comment]
It is due to a "null pointer exception" [when getting search params](https://github.com/beenotung/ts-liveview/blob/e95afe17ec2afea0a648ce30c9ca506995df3484/server/app/pages/editor.tsx#L49). This problem is fixed in newer version, I will update the server deployment.

**Comment by beenotung** [comment]
The problem is fixed.

I'm setting up eslint to avoid using non-null assertions :muscle:

**Comment by beenotung** [comment]
The repo is not using non-null assertions now, along with other harden suggested by eslint. We shall close this issue and move on to others?

Reference: https://github.com/beenotung/ts-liveview/commit/ebb0d73c731af270c38c9c581a5910dda217b1a0

**Comment by hpvd** [comment]
works great!
