### ISSUE TITLE
howto: global css styling

### ISSUE THREAD

**Issue by hpvd** [beenotung/ts-liveview#5]
awesome project!

from practical pov: would be nice to see in the example (https://liveviews.cc/) how some simple global styling (the same for every page) would be done best

e.g.

```
h2 {
  font-family: sans-serif;
}

p {
  font-family: serif;
}

table {
  font-family: monospace;
}
```

**Comment by beenotung** [comment]
The current version of demo put the global style inline in the [app.tsx](https://github.com/beenotung/ts-liveview/blob/v2.4.0/server/app/app.tsx#L38-L45)

Thanks for your question and appreciation

**Comment by hpvd** [comment]
ah, thanks for directly pointing to it.

**Comment by beenotung** [comment]
feel free to re-open the issue if you have further questions about global styling
