### ISSUE TITLE
demo: tiny seo opt

### ISSUE THREAD

**Issue by hpvd** [beenotung/ts-liveview#7]
Since your tech is great for seo and you are directly referring to it on https://liveviews.cc/home

> And it's ideal for SEO.

with one thing it could be improved further:
just make this page non-exist, because it's duplicate content:
https://liveviews.cc/home
https://liveviews.cc

=> menu entry `home` should directly link to https://liveviews.cc  :-)

**Comment by beenotung** [comment]
Agree your suggestion, that was to demo having multiple route resolve to same content but that seems non-necessary.

**Comment by beenotung** [comment]
Just updated menu link in the demo.

Thanks for your suggestion and welcome for more ideas :)

**Comment by hpvd** [comment]
there is as small relic alive: a link on https://liveviews.cc/about pointing to /home

**Comment by beenotung** [comment]
Good catch! Also updated the redirection url of source.

(the source link is now pointing to source code when viewing from github, but pointing to live demo of corresponding page when viewing from demo site, as suggested in another issue, future version may really show the source code)

**Comment by beenotung** [comment]
Thanks for your advice, feel free to re-open this issue when you've further suggestions.
